---
- name: Add docker repository key
  become: true
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add docker repository
  become: true
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
    state: present
    update_cache: true

- name: Install docker packages
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - uidmap
    state: present
    update_cache: true

- name: Run dockerd-rootless-setuptool.sh install
  command: /usr/bin/dockerd-rootless-setuptool.sh install
