---
- name: Add docker repository key
  become: true
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add docker repository
  become: true
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
    state: present
    update_cache: true

- name: Install docker packages
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

# see https://blog.chlc.cc/p/docker-and-zfs-a-tough-pair/

- name: Retrieve ZFS version
  command: zfs --version
  register: zfs_version
  ignore_errors: true

- name: Check if ZFS is installed
  set_fact:
    zfs_installed: "{{ zfs_version.rc == 0 }}"

- block:
    - name: Stop Docker service
      become: true
      service:
        name: docker
        state: stopped
    - name: Retrieve ZFS dataset information
      command: zfs list -H -o name
      register: zfs_datasets
    - name: Extract dataset suffix
      set_fact:
        zfs_dataset_suffix: "{{ zfs_datasets.stdout_lines | select('match', '^rpool/ROOT/.*/var/lib$') | map('regex_replace', '^rpool/ROOT/(.*)/var/lib$', '\\1') | first }}"
    - name: Display dataset suffix
      debug:
        var: zfs_dataset_suffix
    - name: Create ZFS dataset
      become: true
      command: zfs create -sV 64G rpool/ROOT/{{ zfs_dataset_suffix }}/var/lib/docker
      register: zfs_create_dataset
      failed_when: zfs_create_dataset.rc != 0 and "dataset already exists" not in zfs_create_dataset.stderr
      changed_when: zfs_create_dataset.rc == 0
    - name: Mount ZFS dataset
      become: true
      mount:
        src: /dev/zvol/rpool/ROOT/{{ zfs_dataset_suffix }}/var/lib/docker
        path: /var/lib/docker
        fstype: ext4
        opts: rw
        state: mounted
    - name: Add fstab entry
      become: true
      blockinfile:
        path: /etc/fstab
        state: present
        block: |
          /dev/zvol/rpool/ROOT/{{ zfs_dataset_suffix }}/var/lib/docker	/var/lib/docker	ext4	defaults	0	0
  when: zfs_installed

- name: Start Docker service
  become: true
  service:
    name: docker
    state: started